### ISSUE TITLE
Add correct comment characters to UX files

### ISSUE THREAD

**Issue by SeanAsby** [sergiirocks/vscode-fuse-syntax#1]
First of all nice work getting some Fuse support for Visual Studio code. I use it every day at my work. I would like to contribute to this repo but I have limited knowledge on how tmLanguage files work. 

One thing I'm missing is correct comment behavior in UX files. (When clicking 'cmd' + '-' on MacOS). It is putting two forward slashes in front of each line instead of using XML comments - `<!-- My comment -->`

Maybe you know how this could be fixed?

**Comment by iamsergii** [comment]
fixed in 1.1.1

**Comment by SeanAsby** [comment]
The latest patch broke block comments for inline JavaScript in UX.

**Comment by iamsergii** [comment]
You can’t have both of them in vscode (there is no way to switch default behavior for commenting within the js tag, at least as far as I know). I feel like it is right to have xml-like comments inside ux files. If you want to be able to comment in js, extract the js code to a separate file

## 

Sergii

**Comment by SeanAsby** [comment]
Ok. I just know that in the official Sublime plugin from Fuse they manage it somehow. But if its not supported in vscode i guess there is nothing to do.

**Comment by iamsergii** [comment]
Yeah, it’s a long hanging issue in the vscode, it is broken since 0.10.2 when they switched the internal js parser and it is not fixed until now
